import Head from "next/head";
import Link from "next/link";
import { FaGithub } from "react-icons/fa";
import { FaTwitter } from "react-icons/fa";
import { FaInstagram } from "react-icons/fa";
import React, { useState, useEffect } from "react";
import useFetchData from "@/hooks/useFetchData";
import { SiCoursera } from "react-icons/si";
import { BiSolidMoviePlay } from "react-icons/bi";
import { GrResources } from "react-icons/gr";
import { FaComputer } from "react-icons/fa6";
import { GiGameConsole } from "react-icons/gi";
import { CgTemplate } from "react-icons/cg";
import { FaMobileScreen } from "react-icons/fa6";



import parse from "html-react-parser";

function extractFirstImageUrl(markdownContent) {
  // Check if markdownContent is provided and non-empty
  if (!markdownContent || typeof markdownContent !== "string") {
    return null;
  }

  // Regular expression to match the first image URL in markdown format ![alt text](imageURL)
  const regex = /!\[.*?\]\((.*?)\)/;
  const match = markdownContent.match(regex);
  return match ? match[1] : null;
}

export default function Home() {
  const [currentPage, setCurrentPage] = useState(1);
  const [perPage] = useState(5);
  const { alldata, loading, error } = useFetchData(`/api/getblog`);

  if (error) return <p>{error}</p>; // Display error message

  // Function to handle page change
  const paginate = (pageNumber) => {
    setCurrentPage(pageNumber);
  };

  const indexOfLastblog = currentPage * perPage;
  const indexOfFirstblog = indexOfLastblog - perPage;
  const currentBlogs = alldata.slice(indexOfFirstblog, indexOfLastblog);

  const allblog = alldata.length; // Total number of blogs

  // Filtering publish blogs
  const publishedblogs = currentBlogs.filter((ab) => ab.status === "publish");

  const pageNumbers = [];

  for (let i = 1; i <= Math.ceil(allblog / perPage); i++) {
    pageNumbers.push(i);
  }

  return (
    <>
      <Head>
        <title>AIO PORTAL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="header_data_section">
        <div className="container flex flex-sb w-100">
          <div className="leftheader_info" data-aos="fade-right">
            <h1>
              Welcome to <span>AIO PORTAL</span>.
            </h1>
            <h3>
              Discover AIO Portal – your all-in-one destination where everything
              is free! From resources to tools, and endless content, find
              anything you're looking for, all in one place.
            </h3>
            {/* <div className="flex gap-2 ">
              <Link href='/contact'><button>Contact Me</button></Link>
              <Link href='/about'><button>About Me</button></Link>
            </div> */}
          </div>
          {/* <div className="rightheader_img" data-aos="zoom-in">
            <div className="image_bg_top"></div>
            <div className="image_bg_top2"></div>
            <img src="/img/coder.png" alt="coder" />
          </div> */}
        </div>
      </section>
      <section className="main_blog_section">
        <div className="container flex flex-sb flex-left flex-wrap">
          <div className="leftblog_sec">
            <h2>Recently Published</h2>
            <div className="blogs_sec">
              {loading ? (
                <>
                  <div className="wh-100 flex flex-center mt-2 pb-5">
                    <div
                      aria-live="assertive"
                      role="alert"
                      className="loader"
                    ></div>
                  </div>
                </>
              ) : (
                <>
                  {publishedblogs.map((blog) => {
                    // in the markdown content first image show here
                    const firstImageUrl = extractFirstImageUrl(
                      blog.description
                    );

                    // Function to convert Markdown to plain text
                    const markdownToText = (markdown) => {
                      // Use a simple regex to remove Markdown formatting
                      return markdown
                        .replace(/(\*\*|__)(.*?)\1/g, "$2") // Bold
                        .replace(/(\*|_)(.*?)\1/g, "$2") // Italics
                        .replace(/`([^`]+)`/g, "$1") // Inline code
                        .replace(/!\[.*?\]\(.*?\)/g, "") // Images
                        .replace(/\[.*?\]\(.*?\)/g, "") // Links
                        .replace(/###*|##*|#*/g, "") // Headers
                        .replace(/(\r\n|\n|\r)/g, " ") // New lines
                        .trim(); // Remove extra spaces
                    };

                    const plainTextDescription = markdownToText(
                      blog.description
                    );
                    const truncatedDescription =
                      plainTextDescription.length > 150
                        ? `${plainTextDescription.substring(0, 80)}...`
                        : plainTextDescription;
                    return (
                      <div className="blog" key={blog._id} data-aos="fade-up">
                        <div className="blogimg">
                          <Link href={`/blog/${blog.slug}`}>
                            <img
                              src={firstImageUrl || "/img/noimage.jpg"}
                              alt="blog"
                            />
                          </Link>
                        </div>
                        <div className="bloginfo">
                          <Link href={`/tag/${blog.tags[0]}`}>
                            <div className="blogtag">{blog.tags[0]}</div>
                          </Link>
                          <Link href={`/blog/${blog.slug}`}>
                            <h3>{blog.title}</h3>
                          </Link>

                          {/* Render only the first <p> tag */}
                          <p>{truncatedDescription}</p>
                          <div className="blogauthor flex gap-1">
                            <div className="blogaimg">
                              <img src="/img/coder.png" alt="author" />
                            </div>
                            <div className="flex flex-col flex-left gap-05">
                              <h4>Admin</h4>
                              <span>
                                {new Date(blog.createdAt).toLocaleDateString(
                                  "en-US",
                                  {
                                    month: "long",
                                    day: "numeric",
                                    year: "numeric",
                                  }
                                )}
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </>
              )}
            </div>
            <div className="blogpagination">
              <button
                onClick={() => paginate(currentPage - 1)}
                disabled={currentPage === 1}
              >
                Previous
              </button>
              {pageNumbers
                .slice(
                  Math.max(currentPage - 3, 0),
                  Math.min(currentPage + 2, pageNumbers.length)
                )
                .map((number) => (
                  <button
                    key={number}
                    onClick={() => paginate(number)}
                    className={`${currentPage === number ? "active" : ""}`}
                  >
                    {number}
                  </button>
                ))}
              <button
                onClick={() => paginate(currentPage + 1)}
                disabled={currentPage === Math.ceil(allblog / perPage)}
              >
                Next
              </button>
            </div>
          </div>
          <div className="rightblog_info">
            <div className="topics_sec">
              <h2>Topics</h2>
              <div className="topics_list">
                <Link href="/topics/courses" data-aos="fade-up">
                  <div className="topics">
                    <div className="flex flex-center topics_svg">
                      <SiCoursera />
                    </div>
                    <h3>Courses</h3>
                  </div>
                </Link>
                <Link href="/topics/entertainment">
                  <div className="topics">
                    <div className="flex flex-center topics_svg">
                      <BiSolidMoviePlay />
                    </div>
                    <h3>Entertainment</h3>
                  </div>
                </Link>
                <Link href="/topics/graphicresources" data-aos="fade-up">
                  <div className="topics">
                    <div className="flex flex-center topics_svg">
                      <GrResources />
                    </div>
                    <h3>Graphic Resources</h3>
                  </div>
                </Link>
                <Link href="/topics/software" data-aos="fade-up">
                  <div className="topics">
                    <div className="flex flex-center topics_svg">
                      <FaComputer />
                    </div>
                    <h3>Software</h3>
                  </div>
                </Link>
                <Link href="/topics/games" data-aos="fade-up">
                  <div className="topics">
                    <div className="flex flex-center topics_svg">
                      <GiGameConsole />
                    </div>
                    <h3>Games</h3>
                  </div>
                </Link>
                <Link href="/topics/templates" data-aos="fade-up">
                  <div className="topics">
                    <div className="flex flex-center topics_svg">
                      <CgTemplate />
                    </div>
                    <h3>Templates</h3>
                  </div>
                </Link>
                <Link href="/topics/mobileapps" data-aos="fade-up">
                  <div className="topics">
                    <div className="flex flex-center topics_svg">
                      <FaMobileScreen />
                    </div>
                    <h3>Mobile Apps</h3>
                  </div>
                </Link>
              </div>
            </div>
            <div className="tags_sec mt-3">
              <h2>Tags</h2>
              <div className="tags_list" data-aos="fade-up">
                <Link href="/tag/learnandgrow">#learnandgrow</Link>
                <Link href="/tag/creativedesigns">#creativedesigns</Link>
                <Link href="/tag/softwaresolutions">#softwaresolutions</Link>
                <Link href="/tag/gameon">#gameon</Link>
                <Link href="/tag/movies">#movies</Link>
                <Link href="/tag/series">#series</Link>
                <Link href="/tag/anime">#anime</Link>
                <Link href="/tag/graphicassets">#graphicassets</Link>
                <Link href="/tag/techtutorials">#techtutorials</Link>
                <Link href="/tag/gamingcommunity">#gamingcommunity</Link>
                <Link href="/tag/templatelibrary">#templatelibrary</Link>
                <Link href="/tag/resourcecenter">#resourcecenter</Link>
                <Link href="/tag/mobileapps">#mobileapps</Link>
              </div>
            </div>
            <div className="letstalk_sec mt-3">
              <h2>Let's Talk</h2>
              <div className="talk_sec">
                <h4>
                  Want to find out how I can solve problems specific to your
                  business? Let's talk.
                </h4>
                <div className="social_talks flex flex-center gap-1 mt-2">
                  <div className="st_icon" data-aos="fade-up">
                    <FaGithub />
                  </div>
                  <div className="st_icon" data-aos="fade-up">
                    <FaTwitter />
                  </div>
                  <div className="st_icon" data-aos="fade-up">
                    <FaInstagram />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
